In [1]:
import numpy as np
asList = [1,2,3]
asArray = np.array([1,2,3]) # 1D array
rowVec = np.array([ [1,2,3] ]) # row
colVec = np.array([ [1],[2],[3] ]) # column

In [2]:
asArray

array([1, 2, 3])

In [3]:
rowVec

array([[1, 2, 3]])

In [4]:
colVec

array([[1],
       [2],
       [3]])

In [5]:
v = np.array([4,5,6])
w = np.array([10,20,30])
u = np.array([0,3,6,9])
vPlusW = v+w

In [6]:
vPlusW

array([14, 25, 36])